### PR TITLE
➕  Add prettier

### PR DESCRIPTION
**Pull request by saschahaselhuhn**
- Installed prettier with npm i -D prettier
- Added .prettierrc.json with default config
- Added .prettierignore to ignore build artifacts
- Added npm run prettify to format all code
- Prettified all code

https://prettier.io/docs/en/install.html

### CODE REVIEW

**Review by sweisz — APPROVED** [review]
LGTM 👍

**Review by M-Sieger — APPROVED** [review]
LGTM

**Review by RonjaMeinecke — APPROVED** [review]
gj💪

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Comment by HorstFrank** [comment]
TOP!

**Pull request merged**
