### PR TITLE
➕ Add storybook 

### PR DESCRIPTION
**Pull request by saschahaselhuhn**

### CODE REVIEW

**Review by fgottesmann — APPROVED** [review]
Well done!

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by RonjaMeinecke — APPROVED** [review]
GJ🚀

**Review by m-wiemers — APPROVED** [review]
I have a de ja vue 👍

**Review by sweisz — APPROVED** [review]
LGTM 👍

**Pull request merged**
