### PR TITLE
server

### PR DESCRIPTION
**Pull request by saschahaselhuhn**
✨ Add custom server
🔨 Split build script
🐛 Fix build script

### CODE REVIEW

**Review by fgottesmann — APPROVED** [review]
Bueno!

**Comment by JuKahl** [comment]
GJ 🚀

**Review by JuKahl — APPROVED** [review]

**Review by christophvogel — APPROVED** [review]
GJ 💯

**Review by sweisz — APPROVED** [review]
💯

**Review by m-wiemers — APPROVED** [review]
What is it? Is that a chicken? No, it is Sascha Superhacker 💻

**Review by cboenke — APPROVED** [review]
GJ 🚀

**Pull request merged**
